### ISSUE TITLE
issues with python 3

### ISSUE THREAD

**Issue by hennyu** [openzoom/deepzoom.py#18]
Hi,
is it possible to install and run deepzoom.py with python 3? I get some errors, for example that there is no module StringIO and that xrange is not defined.
Trying to run it with Python 2.7; I also get errors. I used the module some years ago and it worked (so I'll try to use an older release as a workaround in the meanwhile)

**Comment by gasi** [comment]
Version 2.0.0 introduced Python 3 support: https://github.com/openzoom/deepzoom.py/blob/f2a1fa746910d1eb7d3ff4877c94385701b482d5/CHANGELOG.md#version-200a1--january-16-2020
