### ISSUE TITLE
Wrong text in generated XML (typo)

### ISSUE THREAD

**Issue by cartoleba** [openzoom/deepzoom.py#8]
Using the latest version obtained in git today I have used the XML generated with Salado Player to display panoramic spherical images. The XML contains a typographic error that causes Salado Player to not find the images. Where it should be writen "xmnls" it is writen "xmlns" to point to the schema at the microsoft site.

**Comment by gasi** [comment]
@cartoleba I just saw this issue now. I’ve never seen `xmnls` as `xmlns` stands for `XML Namespace`, see: https://stackoverflow.com/a/40354480

Please reopen if this issue hasn’t been resolved.
